CREATE TABLE LOGIN_APP_USERS (
  USER_ID INT UNSIGNED NOT NULL,
  USERNAME VARCHAR(20) NOT NULL UNIQUE KEY,
  PASSWORD VARCHAR(100) NOT NULL,
  PRIMARY KEY (USER_ID)
) ENGINE=INNODB;

CREATE TABLE LOGIN_APP_USER_ROLES (
  SEQ_ID INT UNSIGNED NOT NULL,
  USER_ID INT UNSIGNED NOT NULL,
  ROLE INT UNSIGNED NOT NULL,
  PRIMARY KEY (SEQ_ID),
  FOREIGN KEY (USER_ID)
    REFERENCES LOGIN_APP_USERS(USER_ID)
    ON DELETE CASCADE
) ENGINE=INNODB;
